function noisy_record = add_noise_to_signal(audio_record)
    a1 = .025;
    w1 = 6000*2*pi/audio_record.sample_rate; 
    a2 = .03;
    w2 = 7000*2*pi/audio_record.sample_rate;
    a3 = .035;
    w3 = 8000*2*pi/audio_record.sample_rate;

    noisy_record = create_audio_record(  ...
      audio_record.input_device_id, ...
      audio_record.output_device_id, ...
      audio_record.sample_rate, ...
      audio_record.bits ...
    );
    
    t = transpose(0:length(audio_record.data)-1);
    noisy_record.data = audio_record.data ...
        + a1*cos(w1.*t) ...
        + a2*cos(w2.*t) ...
        + a3*cos(w3.*t);
end