function plot_capacitor_waveforms(XData1, YData1, YData2, YData3, Io, delta_I_L)
%CREATEFIGURE(XData1, YData1, YData2, YData3, Parent1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
%  YDATA3:  line ydata
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 08-Dec-2024 10:32:06

% Create figure
fig = figure('Tag','ScopePrintToFigure',...
    'OuterPosition',[782 423.666666666667 998 597.333333333333]);
setFigureProperties(fig);
tiledlayout(3,1);


% Create axes
nexttile
axes1 = gca; %axes('Tag','DisplayAxes1_RealMag');
hold(axes1,'on');
colororder([1 0.909803921568627 0.392156862745098; ...
    0.149019607843137 0.549019607843137 0.866666666666667; ...
    0.96078431372549 0.466666666666667 0.16078431372549; ...
    0.286274509803922 0.858823529411765 0.250980392156863; ...
    0.752941176470588 0.36078431372549 0.984313725490196; ...
    0.423529411764706 0.956862745098039 1; ...
    0.949019607843137 0.403921568627451 0.772549019607843 ...
    ]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData1,'DisplayName','i_L','Tag','DisplayLine1');

yline(Io, '--b', 'I_o = I_L')
yline(Io + delta_I_L/2, '--y')
yline(Io - delta_I_L/2, '--y')

% Create title
title('i_L');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.0355997323345281 0.0357075170883746]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.387876523543555 4.61131882904555]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle',...
    'GridAlpha',0.4, ...
    'GridColor',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'TickLabelInterpreter','none', ...
    'XTickLabel','',...
    'ZColor',[0.686274509803922 0.686274509803922 0.686274509803922]);
% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);




% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
nexttile
axes2 = gca; %axes('Tag','DisplayAxes2_RealMag');
hold(axes2,'on');
colororder([1 0.909803921568627 0.392156862745098;0.149019607843137 0.549019607843137 0.866666666666667;0.96078431372549 0.466666666666667 0.16078431372549;0.286274509803922 0.858823529411765 0.250980392156863;0.752941176470588 0.36078431372549 0.984313725490196;0.423529411764706 0.956862745098039 1;0.949019607843137 0.403921568627451 0.772549019607843]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData2,'DisplayName','i_C','Tag','DisplayLine1',...
    'LineWidth',0.75,...
    'Color',[1 0.909803921568627 0.392156862745098]);

% Create title
title('i_C','FontSize',10,'Interpreter','none');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes2,[0.0355997323345281 0.0357075170883746]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes2,[-2.12955292844154 2.09072836296863]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes2,[-1 1]);
box(axes2,'on');
hold(axes2,'off');
% Set the remaining axes properties
set(axes2,'ClippingStyle','rectangle','Color',[0 0 0],'FontSize',8,...
    'GridAlpha',0.4,'GridColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],...
    'TickLabelInterpreter','none','XColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],'XTickLabel','',...
    'YColor',[0.686274509803922 0.686274509803922 0.686274509803922],'ZColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922]);
% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
nexttile
axes3 = gca; %axes('Tag','DisplayAxes3_RealMag');
hold(axes3,'on');
colororder([1 0.909803921568627 0.392156862745098;0.149019607843137 0.549019607843137 0.866666666666667;0.96078431372549 0.466666666666667 0.16078431372549;0.286274509803922 0.858823529411765 0.250980392156863;0.752941176470588 0.36078431372549 0.984313725490196;0.423529411764706 0.956862745098039 1;0.949019607843137 0.403921568627451 0.772549019607843]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData3,'DisplayName','v_C','Tag','DisplayLine1',...
    'LineWidth',0.75,...
    'Color',[1 0.909803921568627 0.392156862745098]);

% Create xlabel
xlabel(' ');

% Create title
title('v_C','FontSize',10,'Interpreter','none');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes3,[0.0355997323345281 0.0357075170883746]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes3,[47.0822630113285 49.1028779236548]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes3,[-1 1]);
box(axes3,'on');
hold(axes3,'off');
% Set the remaining axes properties
set(axes3,'ClippingStyle','rectangle','Color',[0 0 0],'FontSize',8,...
    'GridAlpha',0.4,'GridColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],...
    'TickLabelInterpreter','none','XColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],'YColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922],'ZColor',...
    [0.686274509803922 0.686274509803922 0.686274509803922]);
% Create text
text('Tag','TimeOffsetStatus','Units','pixels',...
    'VerticalAlignment','bottom',...
    'FontSize',8,...
    'Position',[0 0 0],...
    'Color',[0.686274509803922 0.686274509803922 0.686274509803922],...
    'Visible','on');

