function parameters = single_phase_equivalent_circuit(Rwinding, X1, R2prime, X2prime, Xmag, Rrot)
%SINGLE_PHASE_EQUIVALENT_CIRCUIT Summary of this function goes here
%   Detailed explanation goes here
parameters = struct(...
    "R1", Rwinding, ...
    "X1", X1, ...
    "R2prime", R2prime, ...
    "X2prime", X2prime, ...
    "Xmag", Xmag, ...
    "R_rot", Rrot);
end

